[tool.poetry]
name = "codetri-webhook"
version = "0.1.0"
description = ""
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1"
python-dotenv = "^0.10.3"
gunicorn = "^20.0"
supervisor = "^4.1.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
